spring.application.name=gold-price-api
spring.datasource.url=jdbc:h2:mem:gold_price_db;MODE=MySQL;DATABASE_TO_UPPER=false
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.jackson.serialization.write-dates-as-timestamps=false
